# Generated by Django 5.1.6 on 2025-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
    ]
