# Generated by Django 5.1.6 on 2025-02-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_students_dob_students_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
    ]
